#pragma once

#include <Generic.h>
#include <Updatable.h>
#include <GMath.h>

enum class Key
{
	Unknown = -1,
	A = 0x41,
	B = 0x42,
	C = 0x43,
	D = 0x44,
	E = 0x45,
	F = 0x46,
	G = 0x47,
	H = 0x48,
	I = 0x49,
	J = 0x4A,
	K = 0x4B,
	L = 0x4C,
	M = 0x4D,
	N = 0x4E,
	O = 0x4F,
	P = 0x50,
	Q = 0x51,
	R = 0x52,
	S = 0x53,
	T = 0x54,
	U = 0x55,
	V = 0x56,
	W = 0x57,
	X = 0x58,
	Y = 0x59,
	Z = 0x5A,
	Zero = 0x30,
	One = 0x31,
	Two = 0x32,
	Three = 0x33,
	Four = 0x34,
	Five = 0x35,
	Six = 0x36,
	Seven = 0x37,
	Eight = 0x38,
	Nine = 0x39,
	Escape = VK_ESCAPE,
	LControl = VK_LCONTROL,
	LShift = VK_LSHIFT,
	LAlt = VK_LMENU,
	LSystem = VK_LWIN,
	RControl = VK_RCONTROL,
	RShift = VK_RSHIFT,
	RAlt = VK_RMENU,
	RSystem = VK_RWIN,
	Menu = VK_APPS,
	LBracket = VK_OEM_4,
	RBracket = VK_OEM_6,
	SemiColon = VK_OEM_1,
	Comma = VK_OEM_COMMA,
	Period = VK_OEM_PERIOD,
	Quote = VK_OEM_7,
	Slash = VK_OEM_2,
	BackSlash = VK_OEM_5,
	Tilde = VK_OEM_3,
	Equal = VK_OEM_PLUS,
	Dash = VK_OEM_MINUS,
	Space = VK_SPACE,
	Return = VK_RETURN,
	BackSpace = VK_BACK,
	Tab = VK_TAB,
	PageUp = VK_PRIOR,
	PageDown = VK_NEXT,
	End = VK_END,
	Home = VK_HOME,
	Insert = VK_INSERT,
	Delete = VK_DELETE,
	Add = VK_ADD,
	Subtract = VK_SUBTRACT,
	Multiply = VK_MULTIPLY,
	Divide = VK_DIVIDE,
	Left = VK_LEFT,
	Right = VK_RIGHT,
	Up = VK_UP,
	Down = VK_DOWN,
	NumpadZero = VK_NUMPAD0,
	NumpadOne = VK_NUMPAD1,
	NumpadTwo = VK_NUMPAD2,
	NumpadThree = VK_NUMPAD3,
	NumpadFour = VK_NUMPAD4,
	NumpadFive = VK_NUMPAD5,
	NumpadSix = VK_NUMPAD6,
	NumpadSeven = VK_NUMPAD7,
	NumpadEight = VK_NUMPAD8,
	NumpadNine = VK_NUMPAD9,
	F1 = VK_F1,
	F2 = VK_F2,
	F3 = VK_F3,
	F4 = VK_F4,
	F5 = VK_F5,
	F6 = VK_F6,
	F7 = VK_F7,
	F8 = VK_F8,
	F9 = VK_F9,
	F10 = VK_F10,
	F11 = VK_F11,
	F12 = VK_F12,
	F13 = VK_F13,
	F14 = VK_F14,
	F15 = VK_F15,
	Pause = VK_PAUSE,
	Count = 102
};

class Input
{
public:
	CPPGAPI static bool IsKeyDown(Key key);
	CPPGAPI static bool IsKeyPressed(Key key);
	CPPGAPI static bool IsKeyReleased(Key key);

	static void Update();

private:
	static bool keyStates[(int)Key::Count];
	static bool keyStatesPrev[(int)Key::Count];
};